import esbuild from "esbuild";
import process from "process";
import path from "path";
import builtins from "builtin-modules";

const prod = process.argv[2] === "production";

const vaultPath = process.env.OBSIDIAN_VAULT;

// Output to root folder in production, or to vault plugins folder in dev
const outdir = prod
  ? '.'
  : path.join(
      vaultPath,
      '.obsidian/plugins/obsidian-sna'
    );

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const ctx = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: path.join(outdir, "main.js"),

  banner: {
    js: banner,
  },

  external: [
    "obsidian",
    "electron",
    ...builtins,
  ],

  platform: "browser",
  format: "cjs",
  target: "es2018",

  sourcemap: prod ? false : "inline",
  treeShaking: true,
  logLevel: "info",

  loader: {
    ".ts": "ts",
  },
});

if (prod) {
  await ctx.rebuild();
  await ctx.dispose();
} else {
  await ctx.watch();

  console.log("Watching for changes...");
}
