
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SNAPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/views/SNAView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_SNA = "sna-view";
var SNAView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.currentNormalizationOptions = { ...plugin.settings.normalizationOptions };
  }
  getViewType() {
    return VIEW_TYPE_SNA;
  }
  getDisplayText() {
    return "Social Network Analysis";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    const content = container.createDiv({ cls: "sna-container" });
    content.createEl("h1", { text: "Social Network Analysis" });
    content.createEl("p", {
      text: "Analyze the structure and relationships in your Obsidian graph."
    });
    const buttonContainer = content.createDiv({ cls: "button-container" });
    const analyzeBtn = buttonContainer.createEl("button", {
      text: "Analyze Graph"
    });
    analyzeBtn.addEventListener("click", async () => {
      const results = await this.plugin.graphAnalyzer.analyzeCurrentGraph(
        this.currentNormalizationOptions
      );
      if (results) {
        this.displayResults(content, results);
      }
    });
    const exportBtn = buttonContainer.createEl("button", {
      text: "Export Results"
    });
    exportBtn.addEventListener("click", async () => {
      await this.plugin.graphAnalyzer.exportResults();
    });
    const normalizationDiv = content.createDiv({ cls: "normalization-toggles" });
    normalizationDiv.createEl("h3", { text: "Normalization Options" });
    normalizationDiv.createEl("p", {
      text: "Toggle normalization on/off for each metric to compare raw vs normalized values:"
    });
    const togglesContainer = normalizationDiv.createDiv({ cls: "toggles-grid" });
    const metrics = [
      { key: "degreeCentrality", label: "Degree Centrality" },
      { key: "betweennessCentrality", label: "Betweenness Centrality" },
      { key: "eigenvectorCentrality", label: "Eigenvector Centrality" },
      { key: "closenessCentrality", label: "Closeness Centrality" },
      { key: "pageRank", label: "PageRank" },
      { key: "harmonicCentrality", label: "Harmonic Centrality" },
      { key: "clusteringCoefficient", label: "Clustering Coefficient" }
    ];
    metrics.forEach(({ key, label }) => {
      var _a;
      const toggleDiv = togglesContainer.createDiv({ cls: "toggle-item" });
      toggleDiv.createEl("label", {
        text: label,
        cls: "toggle-label"
      });
      const checkbox = toggleDiv.createEl("input", {
        type: "checkbox",
        cls: "toggle-checkbox"
      });
      checkbox.checked = (_a = this.currentNormalizationOptions[key]) != null ? _a : true;
      checkbox.addEventListener("change", () => {
        this.currentNormalizationOptions[key] = checkbox.checked;
      });
      const statusSpan = toggleDiv.createEl("span", {
        text: checkbox.checked ? "Normalized" : "Raw",
        cls: "toggle-status"
      });
      checkbox.addEventListener("change", () => {
        statusSpan.textContent = checkbox.checked ? "Normalized" : "Raw";
      });
    });
    const settingsDiv = content.createDiv({ cls: "settings-info" });
    settingsDiv.createEl("h3", { text: "Current Settings" });
    const settings = settingsDiv.createEl("ul");
    settings.createEl("li", {
      text: `Directional Analysis: ${this.plugin.settings.enableDirectional ? "Enabled" : "Disabled"}`
    });
    settings.createEl("li", {
      text: `Weighted Links: ${this.plugin.settings.enableWeightedLinks ? "Enabled" : "Disabled"}`
    });
    settings.createEl("li", {
      text: `Clustering: ${this.plugin.settings.enableClustering ? "Enabled" : "Disabled"}`
    });
    settings.createEl("li", {
      text: `Layout Algorithm: ${this.plugin.settings.layoutAlgorithm}`
    });
  }
  displayResults(container, results) {
    const oldResults = container.querySelector(".results-container");
    if (oldResults) {
      oldResults.remove();
    }
    const resultsDiv = container.createDiv({ cls: "results-container" });
    resultsDiv.createEl("h2", { text: "Analysis Results" });
    const tabs = resultsDiv.createDiv({ cls: "tabs" });
    this.createResultTab(
      tabs,
      "Degree Centrality",
      results.degreeCentrality
    );
    this.createResultTab(
      tabs,
      "Betweenness Centrality",
      results.betweennessCentrality
    );
    this.createResultTab(
      tabs,
      "Eigenvector Centrality",
      results.eigenvectorCentrality
    );
    this.createResultTab(
      tabs,
      "Closeness Centrality",
      results.closenessCentrality
    );
    this.createResultTab(tabs, "PageRank", results.pageRank);
    this.createResultTab(
      tabs,
      "Harmonic Centrality",
      results.harmonicCentrality
    );
    this.createResultTab(
      tabs,
      "Clustering Coefficient",
      results.clusteringCoefficient
    );
  }
  createResultTab(container, title, data) {
    const tabDiv = container.createDiv({ cls: "result-tab" });
    tabDiv.createEl("h3", { text: title });
    const table = tabDiv.createEl("table");
    const header = table.createTHead().insertRow();
    header.insertCell(0).textContent = "Node";
    header.insertCell(1).textContent = "Score";
    const sorted = Array.from(data.entries()).sort((a, b) => b[1] - a[1]).slice(0, 15);
    const tbody = table.createTBody();
    sorted.forEach(([node, value]) => {
      const row = tbody.insertRow();
      row.insertCell(0).textContent = node;
      row.insertCell(1).textContent = value.toFixed(4);
    });
  }
  async onClose() {
  }
};

// src/utils/SNACalculator.ts
var MAX_ITERATIONS = 100;
var CONVERGENCE_THRESHOLD = 1e-6;
var PAGERANK_DAMPING = 0.85;
var SNACalculator = class {
  buildAdjacency(nodes, edges, directed) {
    const adj = /* @__PURE__ */ new Map();
    nodes.forEach((node) => adj.set(node.id, /* @__PURE__ */ new Set()));
    edges.forEach((edge) => {
      var _a, _b;
      (_a = adj.get(edge.source)) == null ? void 0 : _a.add(edge.target);
      if (!directed) {
        (_b = adj.get(edge.target)) == null ? void 0 : _b.add(edge.source);
      }
    });
    return adj;
  }
  calculateAllCentrality(nodes, edges, directed = false, normalizationOptions) {
    var _a, _b, _c, _d, _e, _f, _g;
    if (!nodes.length) {
      throw new Error("No nodes supplied for centrality analysis");
    }
    const adjacency = this.buildAdjacency(nodes, edges, directed);
    const options = {
      degreeCentrality: (_a = normalizationOptions == null ? void 0 : normalizationOptions.degreeCentrality) != null ? _a : true,
      betweennessCentrality: (_b = normalizationOptions == null ? void 0 : normalizationOptions.betweennessCentrality) != null ? _b : false,
      eigenvectorCentrality: (_c = normalizationOptions == null ? void 0 : normalizationOptions.eigenvectorCentrality) != null ? _c : false,
      closenessCentrality: (_d = normalizationOptions == null ? void 0 : normalizationOptions.closenessCentrality) != null ? _d : true,
      pageRank: (_e = normalizationOptions == null ? void 0 : normalizationOptions.pageRank) != null ? _e : false,
      harmonicCentrality: (_f = normalizationOptions == null ? void 0 : normalizationOptions.harmonicCentrality) != null ? _f : false,
      clusteringCoefficient: (_g = normalizationOptions == null ? void 0 : normalizationOptions.clusteringCoefficient) != null ? _g : true
    };
    return {
      degreeCentrality: this.calculateDegreeCentrality(nodes, edges, directed, options.degreeCentrality),
      betweennessCentrality: this.calculateBetweennessCentrality(nodes, adjacency, directed, options.betweennessCentrality),
      eigenvectorCentrality: this.calculateEigenvectorCentrality(nodes, edges, directed, options.eigenvectorCentrality),
      closenessCentrality: this.calculateClosenessCentrality(nodes, adjacency, options.closenessCentrality),
      pageRank: this.calculatePageRank(nodes, edges, directed, options.pageRank),
      harmonicCentrality: this.calculateHarmonicCentrality(nodes, adjacency, options.harmonicCentrality),
      clusteringCoefficient: this.calculateClusteringCoefficient(nodes, adjacency, directed)
    };
  }
  calculateDegreeCentrality(nodes, edges, directed = false, normalize = true) {
    const centrality = /* @__PURE__ */ new Map();
    nodes.forEach((node) => centrality.set(node.id, 0));
    edges.forEach((edge) => {
      centrality.set(
        edge.source,
        (centrality.get(edge.source) || 0) + edge.weight
      );
      if (!directed) {
        centrality.set(
          edge.target,
          (centrality.get(edge.target) || 0) + edge.weight
        );
      }
    });
    if (normalize) {
      const maxDegree = Math.max(...Array.from(centrality.values()), 1);
      centrality.forEach((value, key) => {
        centrality.set(key, value / maxDegree);
      });
    }
    return centrality;
  }
  calculateBetweennessCentrality(nodes, adj, directed = false, normalize = false) {
    const centrality = /* @__PURE__ */ new Map();
    const nodeIds = nodes.map((n) => n.id);
    nodeIds.forEach((id) => centrality.set(id, 0));
    for (const source of nodeIds) {
      const stack = [];
      const predecessors = /* @__PURE__ */ new Map();
      const sigma = /* @__PURE__ */ new Map();
      const dist = /* @__PURE__ */ new Map();
      nodeIds.forEach((v) => {
        predecessors.set(v, []);
        sigma.set(v, 0);
        dist.set(v, -1);
      });
      sigma.set(source, 1);
      dist.set(source, 0);
      const queue = [source];
      while (queue.length > 0) {
        const v = queue.shift();
        stack.push(v);
        for (const w of adj.get(v) || []) {
          if (dist.get(w) < 0) {
            queue.push(w);
            dist.set(w, dist.get(v) + 1);
          }
          if (dist.get(w) === dist.get(v) + 1) {
            sigma.set(w, sigma.get(w) + sigma.get(v));
            predecessors.get(w).push(v);
          }
        }
      }
      const delta = /* @__PURE__ */ new Map();
      nodeIds.forEach((v) => delta.set(v, 0));
      while (stack.length > 0) {
        const w = stack.pop();
        for (const v of predecessors.get(w) || []) {
          const sigmaW = sigma.get(w);
          if (sigmaW !== 0) {
            const contribution = sigma.get(v) / sigmaW * (1 + delta.get(w));
            delta.set(v, delta.get(v) + contribution);
          }
        }
        if (w !== source) {
          centrality.set(
            w,
            centrality.get(w) + delta.get(w)
          );
        }
      }
    }
    if (!directed) {
      centrality.forEach((value, key) => {
        centrality.set(key, value / 2);
      });
    }
    if (normalize) {
      const maxVal = Math.max(...Array.from(centrality.values()), 1);
      centrality.forEach((value, key) => {
        centrality.set(key, value / maxVal);
      });
    }
    return centrality;
  }
  calculateEigenvectorCentrality(nodes, edges, directed = false, normalize = false) {
    const nodeIds = nodes.map((n) => n.id);
    const adjacency = /* @__PURE__ */ new Map();
    nodeIds.forEach((id) => adjacency.set(id, /* @__PURE__ */ new Map()));
    edges.forEach((edge) => {
      const sourceMap = adjacency.get(edge.source);
      sourceMap.set(
        edge.target,
        (sourceMap.get(edge.target) || 0) + edge.weight
      );
      if (!directed) {
        const targetMap = adjacency.get(edge.target);
        targetMap.set(
          edge.source,
          (targetMap.get(edge.source) || 0) + edge.weight
        );
      }
    });
    const centrality = /* @__PURE__ */ new Map();
    nodeIds.forEach((id) => {
      centrality.set(id, 1 / nodeIds.length);
    });
    const rawValues = /* @__PURE__ */ new Map();
    for (let iter = 0; iter < MAX_ITERATIONS; iter++) {
      const next = /* @__PURE__ */ new Map();
      let norm = 0;
      for (const node of nodeIds) {
        let score = 0;
        for (const [neighbor, weight] of adjacency.get(node) || []) {
          score += weight * (centrality.get(neighbor) || 0);
        }
        next.set(node, score);
        norm += score * score;
      }
      norm = Math.sqrt(norm) || 1;
      let maxDiff = 0;
      for (const node of nodeIds) {
        const normalized = (next.get(node) || 0) / norm;
        maxDiff = Math.max(
          maxDiff,
          Math.abs(normalized - (centrality.get(node) || 0))
        );
        centrality.set(node, normalized);
      }
      if (maxDiff < CONVERGENCE_THRESHOLD) {
        break;
      }
    }
    centrality.forEach((value, key) => {
      rawValues.set(key, value);
    });
    if (normalize) {
      const maxVal = Math.max(...Array.from(rawValues.values()), 1);
      rawValues.forEach((value, key) => {
        centrality.set(key, value / maxVal);
      });
    }
    return centrality;
  }
  calculateClosenessCentrality(nodes, adj, normalize = true) {
    const centrality = /* @__PURE__ */ new Map();
    for (const node of nodes) {
      const dist = this.bfsDistances(node.id, adj);
      let totalDist = 0;
      dist.forEach((d) => {
        totalDist += d;
      });
      centrality.set(
        node.id,
        totalDist > 0 ? (dist.size - 1) / totalDist : 0
      );
    }
    if (normalize) {
      const maxVal = Math.max(...Array.from(centrality.values()), 1);
      centrality.forEach((value, key) => {
        centrality.set(key, value / maxVal);
      });
    }
    return centrality;
  }
  calculatePageRank(nodes, edges, directed = false, normalize = false) {
    const nodeIds = nodes.map((n2) => n2.id);
    const n = nodeIds.length;
    const pageRank = /* @__PURE__ */ new Map();
    const outDegree = /* @__PURE__ */ new Map();
    const incoming = /* @__PURE__ */ new Map();
    nodeIds.forEach((id) => {
      pageRank.set(id, 1 / n);
      outDegree.set(id, 0);
      incoming.set(id, []);
    });
    edges.forEach((edge) => {
      var _a, _b;
      outDegree.set(
        edge.source,
        (outDegree.get(edge.source) || 0) + edge.weight
      );
      (_a = incoming.get(edge.target)) == null ? void 0 : _a.push({
        source: edge.source,
        weight: edge.weight
      });
      if (!directed) {
        outDegree.set(
          edge.target,
          (outDegree.get(edge.target) || 0) + edge.weight
        );
        (_b = incoming.get(edge.source)) == null ? void 0 : _b.push({
          source: edge.target,
          weight: edge.weight
        });
      }
    });
    for (let iter = 0; iter < MAX_ITERATIONS; iter++) {
      const next = /* @__PURE__ */ new Map();
      let maxDiff = 0;
      for (const node of nodeIds) {
        let rank = (1 - PAGERANK_DAMPING) / n;
        for (const edge of incoming.get(node) || []) {
          const sourceRank = pageRank.get(edge.source) || 0;
          const degree = outDegree.get(edge.source) || 1;
          rank += PAGERANK_DAMPING * (sourceRank / degree) * edge.weight;
        }
        next.set(node, rank);
        maxDiff = Math.max(
          maxDiff,
          Math.abs(rank - (pageRank.get(node) || 0))
        );
      }
      next.forEach((value, key) => {
        pageRank.set(key, value);
      });
      if (maxDiff < CONVERGENCE_THRESHOLD) {
        break;
      }
    }
    if (normalize) {
      const maxVal = Math.max(...Array.from(pageRank.values()), 1);
      pageRank.forEach((value, key) => {
        pageRank.set(key, value / maxVal);
      });
    }
    return pageRank;
  }
  calculateHarmonicCentrality(nodes, adj, normalize = false) {
    const centrality = /* @__PURE__ */ new Map();
    for (const node of nodes) {
      const dist = this.bfsDistances(node.id, adj);
      let score = 0;
      dist.forEach((d, key) => {
        if (key !== node.id && d > 0) {
          score += 1 / d;
        }
      });
      centrality.set(node.id, score);
    }
    if (normalize) {
      const maxVal = Math.max(...Array.from(centrality.values()), 1);
      centrality.forEach((value, key) => {
        centrality.set(key, value / maxVal);
      });
    }
    return centrality;
  }
  calculateClusteringCoefficient(nodes, adj, directed = false) {
    var _a, _b;
    const coefficients = /* @__PURE__ */ new Map();
    for (const node of nodes) {
      const neighbors = Array.from(adj.get(node.id) || []);
      const k = neighbors.length;
      if (k < 2) {
        coefficients.set(node.id, 0);
        continue;
      }
      let links = 0;
      for (let i = 0; i < neighbors.length; i++) {
        for (let j = i + 1; j < neighbors.length; j++) {
          const ni = neighbors[i];
          const nj = neighbors[j];
          if ((_a = adj.get(ni)) == null ? void 0 : _a.has(nj)) {
            links++;
          }
          if (directed && ((_b = adj.get(nj)) == null ? void 0 : _b.has(ni))) {
            links++;
          }
        }
      }
      const possible = directed ? k * (k - 1) : k * (k - 1) / 2;
      coefficients.set(node.id, possible > 0 ? links / possible : 0);
    }
    return coefficients;
  }
  bfsDistances(source, adj) {
    const dist = /* @__PURE__ */ new Map();
    const queue = [source];
    dist.set(source, 0);
    while (queue.length > 0) {
      const current = queue.shift();
      for (const neighbor of adj.get(current) || []) {
        if (!dist.has(neighbor)) {
          dist.set(
            neighbor,
            dist.get(current) + 1
          );
          queue.push(neighbor);
        }
      }
    }
    return dist;
  }
};

// src/utils/GraphAnalyzer.ts
var import_obsidian2 = require("obsidian");

// src/utils/LayoutEngine.ts
var LayoutEngine = class {
  /**
   * Force-directed layout using Fruchterman-Reingold algorithm
   */
  forceDirectedLayout(nodes, edges, iterations = 100, k = 5) {
    const result = {};
    const positions = /* @__PURE__ */ new Map();
    nodes.forEach((node) => {
      positions.set(node.id, {
        x: Math.random() * 100,
        y: Math.random() * 100,
        vx: 0,
        vy: 0
      });
    });
    const width = 100;
    const height = 100;
    const maxDisplacement = Math.sqrt(width * width + height * height) / 10;
    for (let iter = 0; iter < iterations; iter++) {
      const temperature = maxDisplacement * (1 - iter / iterations);
      nodes.forEach((node) => {
        const pos = positions.get(node.id);
        pos.vx = 0;
        pos.vy = 0;
      });
      for (let i = 0; i < nodes.length; i++) {
        for (let j = i + 1; j < nodes.length; j++) {
          const pos1 = positions.get(nodes[i].id);
          const pos2 = positions.get(nodes[j].id);
          const dx = pos2.x - pos1.x;
          const dy = pos2.y - pos1.y;
          const dist = Math.sqrt(dx * dx + dy * dy) + 0.01;
          const force = k * k / dist;
          const fx = dx / dist * force;
          const fy = dy / dist * force;
          pos1.vx -= fx;
          pos1.vy -= fy;
          pos2.vx += fx;
          pos2.vy += fy;
        }
      }
      edges.forEach((edge) => {
        const pos1 = positions.get(edge.source);
        const pos2 = positions.get(edge.target);
        const dx = pos2.x - pos1.x;
        const dy = pos2.y - pos1.y;
        const dist = Math.sqrt(dx * dx + dy * dy) + 0.01;
        const force = dist * dist / k / edge.weight;
        const fx = dx / dist * force;
        const fy = dy / dist * force;
        pos1.vx += fx;
        pos1.vy += fy;
        pos2.vx -= fx;
        pos2.vy -= fy;
      });
      nodes.forEach((node) => {
        const pos = positions.get(node.id);
        const disp = Math.sqrt(pos.vx * pos.vx + pos.vy * pos.vy);
        if (disp > 0) {
          const delta = Math.min(disp, temperature) / disp;
          pos.x += pos.vx * delta;
          pos.y += pos.vy * delta;
          pos.x = Math.max(0, Math.min(width, pos.x));
          pos.y = Math.max(0, Math.min(height, pos.y));
        }
      });
    }
    nodes.forEach((node) => {
      const pos = positions.get(node.id);
      result[node.id] = { x: pos.x, y: pos.y };
    });
    return result;
  }
  /**
   * Hierarchical layout (top-down tree-like)
   */
  hierarchicalLayout(nodes, edges) {
    const result = {};
    const inDegree = /* @__PURE__ */ new Map();
    nodes.forEach((node) => inDegree.set(node.id, 0));
    edges.forEach((edge) => {
      inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
    });
    const roots = nodes.filter((node) => inDegree.get(node.id) === 0);
    const visited = /* @__PURE__ */ new Set();
    const levels = /* @__PURE__ */ new Map();
    const queue = [];
    roots.forEach((root) => {
      queue.push(root.id);
      levels.set(root.id, 0);
    });
    while (queue.length > 0) {
      const nodeId = queue.shift();
      visited.add(nodeId);
      edges.forEach((edge) => {
        if (edge.source === nodeId && !visited.has(edge.target)) {
          const currentLevel = levels.get(nodeId) || 0;
          levels.set(edge.target, currentLevel + 1);
          queue.push(edge.target);
        }
      });
    }
    const levelCounts = /* @__PURE__ */ new Map();
    const levelPositions = /* @__PURE__ */ new Map();
    nodes.forEach((node) => {
      const level = levels.get(node.id) || 0;
      levelCounts.set(level, (levelCounts.get(level) || 0) + 1);
    });
    nodes.forEach((node) => {
      const level = levels.get(node.id) || 0;
      const count = levelCounts.get(level) || 1;
      const position = (levelPositions.get(level) || 0) + 1;
      levelPositions.set(level, position);
      const x = position / count * 80 + 10;
      const y = level * 20 + 10;
      result[node.id] = { x, y };
    });
    return result;
  }
  /**
   * Circular layout
   */
  circularLayout(nodes) {
    const result = {};
    const n = nodes.length;
    const radius = 40;
    const centerX = 50;
    const centerY = 50;
    nodes.forEach((node, index) => {
      const angle = 2 * Math.PI * index / n;
      const x = centerX + radius * Math.cos(angle);
      const y = centerY + radius * Math.sin(angle);
      result[node.id] = { x, y };
    });
    return result;
  }
};

// src/utils/GraphAnalyzer.ts
var GraphAnalyzer = class {
  constructor(plugin, calculator) {
    this.plugin = plugin;
    this.calculator = calculator;
    this.layoutEngine = new LayoutEngine();
  }
  /**
   * Get the current graph view's query/path filter
   */
  getGraphViewFilter() {
    var _a;
    try {
      const graphLeaves = this.plugin.app.workspace.getLeavesOfType("graph");
      if (graphLeaves && graphLeaves.length > 0) {
        const graphState = (_a = graphLeaves[0].view) == null ? void 0 : _a.state;
        if (graphState && graphState.query) {
          return graphState.query;
        }
      }
    } catch (error) {
      console.error("Error getting graph view filter:", error);
    }
    return null;
  }
  /**
   * Check if a file path matches the graph filter
   */
  matchesFilter(filePath, filter) {
    if (!filter)
      return true;
    if (filter.endsWith("/") || !filter.includes("*")) {
      return filePath.startsWith(filter.replace(/\/$/, ""));
    }
    const regex = new RegExp("^" + filter.replace(/\*/g, ".*") + "$");
    return regex.test(filePath);
  }
  /**
   * Extract graph data from Obsidian's metadataCache using resolvedLinks
   * Respects the current graph view's path filter
   */
  extractGraphData() {
    try {
      const metadataCache = this.plugin.app.metadataCache;
      const vault = this.plugin.app.vault;
      const filter = this.getGraphViewFilter();
      const files = [];
      vault.getMarkdownFiles().forEach((file) => {
        if (file instanceof import_obsidian2.TFile && file.extension === "md") {
          if (this.matchesFilter(file.path, filter)) {
            files.push(file);
          }
        }
      });
      if (files.length === 0) {
        const filterMsg = filter ? ` matching filter "${filter}"` : "";
        new import_obsidian2.Notice(`No markdown files found${filterMsg} in vault.`);
        return null;
      }
      const validPaths = new Set(files.map((f) => f.path));
      const nodeSet = /* @__PURE__ */ new Set();
      const edges = [];
      files.forEach((file) => {
        const filePath = file.path;
        nodeSet.add(filePath);
        const resolvedLinks = metadataCache.resolvedLinks[filePath];
        if (!resolvedLinks)
          return;
        Object.keys(resolvedLinks).forEach((linkedPath) => {
          if (!validPaths.has(linkedPath))
            return;
          nodeSet.add(linkedPath);
          const linkCount = resolvedLinks[linkedPath] || 1;
          edges.push({
            source: filePath,
            target: linkedPath,
            weight: this.plugin.settings.enableWeightedLinks ? linkCount : 1,
            directed: true
          });
        });
      });
      const nodes = Array.from(nodeSet).map((nodePath) => {
        var _a;
        return {
          id: nodePath,
          label: ((_a = nodePath.split("/").pop()) == null ? void 0 : _a.replace(".md", "")) || nodePath
        };
      });
      if (nodes.length === 0) {
        new import_obsidian2.Notice("No nodes found. Check your graph view settings.");
        return null;
      }
      if (edges.length === 0) {
        new import_obsidian2.Notice("No links found. Create some backlinks first.");
        return null;
      }
      console.log(`Extracted ${nodes.length} nodes and ${edges.length} edges`);
      return { nodes, edges };
    } catch (error) {
      new import_obsidian2.Notice("Error extracting graph data: " + error);
      console.error("Graph extraction error:", error);
      return null;
    }
  }
  /**
   * Filter edges based on minimum weight threshold
   */
  filterEdgesByWeight(edges, minWeight) {
    if (!this.plugin.settings.enableWeightedLinks) {
      return edges;
    }
    return edges.filter((edge) => edge.weight >= minWeight);
  }
  /**
   * Analyze the current graph with normalization options
   */
  async analyzeCurrentGraph(normalizationOptions) {
    const graphData = this.extractGraphData();
    if (!graphData)
      return null;
    const { nodes, edges } = graphData;
    if (edges.length === 0) {
      new import_obsidian2.Notice("No edges found in graph.");
      return null;
    }
    const filteredEdges = this.filterEdgesByWeight(
      edges,
      this.plugin.settings.minLinkWeight
    );
    if (filteredEdges.length === 0) {
      new import_obsidian2.Notice("No edges match the minimum weight threshold.");
      return null;
    }
    const options = normalizationOptions || this.plugin.settings.normalizationOptions;
    const results = this.calculator.calculateAllCentrality(
      nodes,
      filteredEdges,
      this.plugin.settings.enableDirectional,
      options
    );
    new import_obsidian2.Notice("Graph analysis complete!");
    return results;
  }
  /**
   * Calculate all centrality metrics
   */
  async calculateAllCentrality() {
    const results = await this.analyzeCurrentGraph();
    if (!results)
      return;
    const message = this.formatResults(results);
    console.log(message);
    if (this.plugin.settings.autoExport) {
      await this.exportResults();
    }
  }
  /**
   * Format results for display
   */
  formatResults(results) {
    let output = "## Social Network Analysis Results\n\n";
    output += this.formatCentralityMap("Degree Centrality", results.degreeCentrality);
    if (this.plugin.settings.enableCloseness) {
      output += this.formatCentralityMap("Closeness Centrality", results.closenessCentrality);
    }
    if (this.plugin.settings.enableBetweenness) {
      output += this.formatCentralityMap(
        "Betweenness Centrality",
        results.betweennessCentrality
      );
    }
    if (this.plugin.settings.enableEigenvector) {
      output += this.formatCentralityMap(
        "Eigenvector Centrality",
        results.eigenvectorCentrality
      );
    }
    if (this.plugin.settings.enablePageRank) {
      output += this.formatCentralityMap("PageRank", results.pageRank);
    }
    if (this.plugin.settings.enableHarmonic) {
      output += this.formatCentralityMap(
        "Harmonic Centrality",
        results.harmonicCentrality
      );
    }
    if (this.plugin.settings.enableClustering) {
      output += this.formatCentralityMap(
        "Clustering Coefficient",
        results.clusteringCoefficient
      );
    }
    return output;
  }
  /**
   * Format a single centrality map
   */
  formatCentralityMap(name, map) {
    let output = `### ${name}

`;
    const sorted = Array.from(map.entries()).sort((a, b) => b[1] - a[1]).slice(0, 20);
    sorted.forEach(([node, value]) => {
      output += `- ${node}: ${value.toFixed(4)}
`;
    });
    output += "\n";
    return output;
  }
  /**
   * Export results to a markdown file
   */
  async exportResults() {
    const results = await this.analyzeCurrentGraph();
    if (!results)
      return;
    const content = this.formatResults(results);
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
    const filename = `SNA-Results-${timestamp}.md`;
    try {
      await this.plugin.app.vault.create(filename, content);
      new import_obsidian2.Notice(`Results exported to ${filename}`);
    } catch (error) {
      new import_obsidian2.Notice("Error exporting results: " + error);
    }
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  enableDirectional: true,
  enableWeightedLinks: true,
  enableClustering: true,
  layoutAlgorithm: "force-directed",
  minLinkWeight: 1,
  autoExport: false,
  enableCloseness: true,
  enableBetweenness: true,
  enableEigenvector: true,
  enablePageRank: true,
  enableHarmonic: true,
  // Default normalization options: industry standard settings
  normalizationOptions: {
    degreeCentrality: true,
    betweennessCentrality: false,
    eigenvectorCentrality: false,
    closenessCentrality: true,
    pageRank: false,
    harmonicCentrality: false,
    clusteringCoefficient: true
  }
};

// src/main.ts
var SNAPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.snaCalculator = new SNACalculator();
    this.graphAnalyzer = new GraphAnalyzer(this, this.snaCalculator);
    this.registerView(VIEW_TYPE_SNA, (leaf) => new SNAView(leaf, this));
    this.addCommand({
      id: "open-sna-view",
      name: "Open Social Network Analysis",
      callback: () => this.activateSNAView()
    });
    this.addCommand({
      id: "analyze-graph",
      name: "Analyze Current Graph",
      callback: () => this.graphAnalyzer.analyzeCurrentGraph()
    });
    this.addCommand({
      id: "calculate-centrality",
      name: "Calculate Centrality Measures",
      callback: () => this.graphAnalyzer.calculateAllCentrality()
    });
    this.addCommand({
      id: "export-analysis",
      name: "Export Analysis Results",
      callback: () => this.graphAnalyzer.exportResults()
    });
    this.addSettingTab(new SNASettingTab(this.app, this));
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateSNAView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_SNA).length > 0 ? workspace.getLeavesOfType(VIEW_TYPE_SNA)[0] : workspace.getUnpinnedLeaf();
    await leaf.setViewState({
      type: VIEW_TYPE_SNA
    });
    workspace.revealLeaf(leaf);
  }
};
var SNASettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Social Network Analysis Settings" });
    new import_obsidian3.Setting(containerEl).setName("Enable Directional Analysis").setDesc("Calculate directional metrics based on backlink direction").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableDirectional).onChange(async (value) => {
        this.plugin.settings.enableDirectional = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable Weighted Links").setDesc("Weight links based on number of mentions").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableWeightedLinks).onChange(async (value) => {
        this.plugin.settings.enableWeightedLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable Clustering").setDesc("Calculate clustering coefficients").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableClustering).onChange(async (value) => {
        this.plugin.settings.enableClustering = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Layout Algorithm").setDesc("Select graph layout algorithm").addDropdown(
      (dropdown) => dropdown.addOption("force-directed", "Force-Directed").addOption("hierarchical", "Hierarchical").addOption("circular", "Circular").setValue(this.plugin.settings.layoutAlgorithm).onChange(async (value) => {
        this.plugin.settings.layoutAlgorithm = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Minimum Link Weight").setDesc("Minimum number of mentions to show a link (when weighted)").addSlider(
      (slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.minLinkWeight).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.minLinkWeight = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Auto-Export Results").setDesc("Automatically export analysis results after calculation").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoExport).onChange(async (value) => {
        this.plugin.settings.autoExport = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Individual Metrics" });
    new import_obsidian3.Setting(containerEl).setName("Enable Closeness Centrality").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCloseness).onChange(async (value) => {
        this.plugin.settings.enableCloseness = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable Betweenness Centrality").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableBetweenness).onChange(async (value) => {
        this.plugin.settings.enableBetweenness = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable Eigenvector Centrality").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableEigenvector).onChange(async (value) => {
        this.plugin.settings.enableEigenvector = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable PageRank").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enablePageRank).onChange(async (value) => {
        this.plugin.settings.enablePageRank = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Enable Harmonic Centrality").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableHarmonic).onChange(async (value) => {
        this.plugin.settings.enableHarmonic = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
