import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const prod = process.argv[2] === "production";

const pluginName = "obsidian-sna";

const vaultPath = process.env.OBSIDIAN_VAULT;

const outdir = prod
  ? 'dist'
  : path.join(
      vaultPath,
      '.obsidian/plugins/obsidian-sna'
    );

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const copyAssets = () => {
  fs.copyFileSync(
    "manifest.json",
    path.join(outdir, "manifest.json")
  );

  if (fs.existsSync("styles.css")) {
    fs.copyFileSync(
      "styles.css",
      path.join(outdir, "styles.css")
    );
  }
};

const ctx = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  outfile: path.join(outdir, "main.js"),

  banner: {
    js: banner,
  },

  external: [
    "obsidian",
    "electron",
    ...builtins,
  ],

  platform: "browser",
  format: "cjs",
  target: "es2018",

  sourcemap: prod ? false : "inline",
  treeShaking: true,
  logLevel: "info",

  loader: {
    ".ts": "ts",
  },
});

if (prod) {
  await ctx.rebuild();
  copyAssets();
  await ctx.dispose();
} else {
  await ctx.watch();
  copyAssets();

  console.log("Watching for changes...");
}
